package com.lee.pojo;

public class ArticleWithBLOBs extends Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.markdown_content
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private String markdownContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.html_content
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private String htmlContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.markdown_content
     *
     * @return the value of article.markdown_content
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public String getMarkdownContent() {
        return markdownContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.markdown_content
     *
     * @param markdownContent the value for article.markdown_content
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setMarkdownContent(String markdownContent) {
        this.markdownContent = markdownContent == null ? null : markdownContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.html_content
     *
     * @return the value of article.html_content
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public String getHtmlContent() {
        return htmlContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.html_content
     *
     * @param htmlContent the value for article.html_content
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setHtmlContent(String htmlContent) {
        this.htmlContent = htmlContent == null ? null : htmlContent.trim();
    }
}