package com.lee.pojo;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.audit_state
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private String auditState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.category
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.author_id
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private Long authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content_type
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private String contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.views
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private Long views;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.approvals
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private Long approvals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.comments
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private Long comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.type_id
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.head_img
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private String headImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.official
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private Byte official;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.top
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private Byte top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.sort
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.marrow
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private Byte marrow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.comment_id
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private Long commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.is_delete
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.create_at
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.update_at
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.audit_state
     *
     * @return the value of article.audit_state
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public String getAuditState() {
        return auditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.audit_state
     *
     * @param auditState the value for article.audit_state
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setAuditState(String auditState) {
        this.auditState = auditState == null ? null : auditState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.category
     *
     * @return the value of article.category
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.category
     *
     * @param category the value for article.category
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.author_id
     *
     * @return the value of article.author_id
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.author_id
     *
     * @param authorId the value for article.author_id
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content_type
     *
     * @return the value of article.content_type
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content_type
     *
     * @param contentType the value for article.content_type
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.views
     *
     * @return the value of article.views
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public Long getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.views
     *
     * @param views the value for article.views
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setViews(Long views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.approvals
     *
     * @return the value of article.approvals
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public Long getApprovals() {
        return approvals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.approvals
     *
     * @param approvals the value for article.approvals
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setApprovals(Long approvals) {
        this.approvals = approvals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.comments
     *
     * @return the value of article.comments
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public Long getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.comments
     *
     * @param comments the value for article.comments
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setComments(Long comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.type_id
     *
     * @return the value of article.type_id
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.type_id
     *
     * @param typeId the value for article.type_id
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.head_img
     *
     * @return the value of article.head_img
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.head_img
     *
     * @param headImg the value for article.head_img
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.official
     *
     * @return the value of article.official
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public Byte getOfficial() {
        return official;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.official
     *
     * @param official the value for article.official
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setOfficial(Byte official) {
        this.official = official;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.top
     *
     * @return the value of article.top
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public Byte getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.top
     *
     * @param top the value for article.top
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setTop(Byte top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.sort
     *
     * @return the value of article.sort
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.sort
     *
     * @param sort the value for article.sort
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.marrow
     *
     * @return the value of article.marrow
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public Byte getMarrow() {
        return marrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.marrow
     *
     * @param marrow the value for article.marrow
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setMarrow(Byte marrow) {
        this.marrow = marrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.comment_id
     *
     * @return the value of article.comment_id
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.comment_id
     *
     * @param commentId the value for article.comment_id
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.is_delete
     *
     * @return the value of article.is_delete
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.is_delete
     *
     * @param isDelete the value for article.is_delete
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.create_at
     *
     * @return the value of article.create_at
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.create_at
     *
     * @param createAt the value for article.create_at
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.update_at
     *
     * @return the value of article.update_at
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.update_at
     *
     * @param updateAt the value for article.update_at
     *
     * @mbggenerated Sat Nov 19 17:49:00 CST 2022
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}