package com.lee.pojo;

import java.util.Date;

public class ArticleType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.id
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.audit_state
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    private String auditState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.name
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.description
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.ref_count
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    private Long refCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.scope
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.creator_id
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.is_delete
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.create_at
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.update_at
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.id
     *
     * @return the value of article_type.id
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.id
     *
     * @param id the value for article_type.id
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.audit_state
     *
     * @return the value of article_type.audit_state
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public String getAuditState() {
        return auditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.audit_state
     *
     * @param auditState the value for article_type.audit_state
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public void setAuditState(String auditState) {
        this.auditState = auditState == null ? null : auditState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.name
     *
     * @return the value of article_type.name
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.name
     *
     * @param name the value for article_type.name
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.description
     *
     * @return the value of article_type.description
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.description
     *
     * @param description the value for article_type.description
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.ref_count
     *
     * @return the value of article_type.ref_count
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public Long getRefCount() {
        return refCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.ref_count
     *
     * @param refCount the value for article_type.ref_count
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public void setRefCount(Long refCount) {
        this.refCount = refCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.scope
     *
     * @return the value of article_type.scope
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.scope
     *
     * @param scope the value for article_type.scope
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.creator_id
     *
     * @return the value of article_type.creator_id
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.creator_id
     *
     * @param creatorId the value for article_type.creator_id
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.is_delete
     *
     * @return the value of article_type.is_delete
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.is_delete
     *
     * @param isDelete the value for article_type.is_delete
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.create_at
     *
     * @return the value of article_type.create_at
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.create_at
     *
     * @param createAt the value for article_type.create_at
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.update_at
     *
     * @return the value of article_type.update_at
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.update_at
     *
     * @param updateAt the value for article_type.update_at
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}