package com.lee.pojo;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.reply_id
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    private Long replyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.reply_reply_id
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    private Long replyReplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.posts_id
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    private Long postsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.is_delete
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.create_at
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.update_at
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.reply_id
     *
     * @return the value of comment.reply_id
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public Long getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.reply_id
     *
     * @param replyId the value for comment.reply_id
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public void setReplyId(Long replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.reply_reply_id
     *
     * @return the value of comment.reply_reply_id
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public Long getReplyReplyId() {
        return replyReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.reply_reply_id
     *
     * @param replyReplyId the value for comment.reply_reply_id
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public void setReplyReplyId(Long replyReplyId) {
        this.replyReplyId = replyReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.posts_id
     *
     * @return the value of comment.posts_id
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public Long getPostsId() {
        return postsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.posts_id
     *
     * @param postsId the value for comment.posts_id
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public void setPostsId(Long postsId) {
        this.postsId = postsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.is_delete
     *
     * @return the value of comment.is_delete
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.is_delete
     *
     * @param isDelete the value for comment.is_delete
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.create_at
     *
     * @return the value of comment.create_at
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.create_at
     *
     * @param createAt the value for comment.create_at
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.update_at
     *
     * @return the value of comment.update_at
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.update_at
     *
     * @param updateAt the value for comment.update_at
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Wed Nov 23 15:11:09 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}