package com.lee.pojo;

public class HasApproval {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column has_approval.id
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column has_approval.article_id
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column has_approval.approvaler_id
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    private Long approvalerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column has_approval.id
     *
     * @return the value of has_approval.id
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column has_approval.id
     *
     * @param id the value for has_approval.id
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column has_approval.article_id
     *
     * @return the value of has_approval.article_id
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column has_approval.article_id
     *
     * @param articleId the value for has_approval.article_id
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column has_approval.approvaler_id
     *
     * @return the value of has_approval.approvaler_id
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    public Long getApprovalerId() {
        return approvalerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column has_approval.approvaler_id
     *
     * @param approvalerId the value for has_approval.approvaler_id
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    public void setApprovalerId(Long approvalerId) {
        this.approvalerId = approvalerId;
    }
}