package com.lee.pojo;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.channel
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.type
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.read
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    private String read;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.sender_type
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    private String senderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.sender
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    private String sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.receiver_type
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    private String receiverType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.receiver
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.title
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content_type
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    private String contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_delete
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_at
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.update_at
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.channel
     *
     * @return the value of message.channel
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.channel
     *
     * @param channel the value for message.channel
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.type
     *
     * @return the value of message.type
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.type
     *
     * @param type the value for message.type
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.read
     *
     * @return the value of message.read
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public String getRead() {
        return read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.read
     *
     * @param read the value for message.read
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public void setRead(String read) {
        this.read = read == null ? null : read.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.sender_type
     *
     * @return the value of message.sender_type
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public String getSenderType() {
        return senderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.sender_type
     *
     * @param senderType the value for message.sender_type
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public void setSenderType(String senderType) {
        this.senderType = senderType == null ? null : senderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.sender
     *
     * @return the value of message.sender
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.sender
     *
     * @param sender the value for message.sender
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.receiver_type
     *
     * @return the value of message.receiver_type
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public String getReceiverType() {
        return receiverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.receiver_type
     *
     * @param receiverType the value for message.receiver_type
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public void setReceiverType(String receiverType) {
        this.receiverType = receiverType == null ? null : receiverType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.receiver
     *
     * @return the value of message.receiver
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.receiver
     *
     * @param receiver the value for message.receiver
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.title
     *
     * @return the value of message.title
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.title
     *
     * @param title the value for message.title
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content_type
     *
     * @return the value of message.content_type
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content_type
     *
     * @param contentType the value for message.content_type
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_delete
     *
     * @return the value of message.is_delete
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_delete
     *
     * @param isDelete the value for message.is_delete
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_at
     *
     * @return the value of message.create_at
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_at
     *
     * @param createAt the value for message.create_at
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.update_at
     *
     * @return the value of message.update_at
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.update_at
     *
     * @param updateAt the value for message.update_at
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated Fri Apr 07 17:35:49 SGT 2023
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}