package com.lee.pojo;

import java.util.Date;

public class Tag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.id
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.audit_state
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    private String auditState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.group_name
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.name
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.description
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.ref_count
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    private Long refCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.creator_id
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.is_delete
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.create_at
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.update_at
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.id
     *
     * @return the value of tag.id
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.id
     *
     * @param id the value for tag.id
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.audit_state
     *
     * @return the value of tag.audit_state
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public String getAuditState() {
        return auditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.audit_state
     *
     * @param auditState the value for tag.audit_state
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public void setAuditState(String auditState) {
        this.auditState = auditState == null ? null : auditState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.group_name
     *
     * @return the value of tag.group_name
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.group_name
     *
     * @param groupName the value for tag.group_name
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.name
     *
     * @return the value of tag.name
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.name
     *
     * @param name the value for tag.name
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.description
     *
     * @return the value of tag.description
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.description
     *
     * @param description the value for tag.description
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.ref_count
     *
     * @return the value of tag.ref_count
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public Long getRefCount() {
        return refCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.ref_count
     *
     * @param refCount the value for tag.ref_count
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public void setRefCount(Long refCount) {
        this.refCount = refCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.creator_id
     *
     * @return the value of tag.creator_id
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.creator_id
     *
     * @param creatorId the value for tag.creator_id
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.is_delete
     *
     * @return the value of tag.is_delete
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.is_delete
     *
     * @param isDelete the value for tag.is_delete
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.create_at
     *
     * @return the value of tag.create_at
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.create_at
     *
     * @param createAt the value for tag.create_at
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.update_at
     *
     * @return the value of tag.update_at
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.update_at
     *
     * @param updateAt the value for tag.update_at
     *
     * @mbggenerated Sat Nov 19 17:35:51 CST 2022
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}