package com.lee.pojo;

import java.util.Date;

public class TagArticleMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_article_mapping.id
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_article_mapping.tag_id
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    private Long tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_article_mapping.posts_id
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    private Long postsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_article_mapping.is_delete
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_article_mapping.create_at
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_article_mapping.update_at
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_article_mapping.id
     *
     * @return the value of tag_article_mapping.id
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_article_mapping.id
     *
     * @param id the value for tag_article_mapping.id
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_article_mapping.tag_id
     *
     * @return the value of tag_article_mapping.tag_id
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_article_mapping.tag_id
     *
     * @param tagId the value for tag_article_mapping.tag_id
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_article_mapping.posts_id
     *
     * @return the value of tag_article_mapping.posts_id
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    public Long getPostsId() {
        return postsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_article_mapping.posts_id
     *
     * @param postsId the value for tag_article_mapping.posts_id
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    public void setPostsId(Long postsId) {
        this.postsId = postsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_article_mapping.is_delete
     *
     * @return the value of tag_article_mapping.is_delete
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_article_mapping.is_delete
     *
     * @param isDelete the value for tag_article_mapping.is_delete
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_article_mapping.create_at
     *
     * @return the value of tag_article_mapping.create_at
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_article_mapping.create_at
     *
     * @param createAt the value for tag_article_mapping.create_at
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_article_mapping.update_at
     *
     * @return the value of tag_article_mapping.update_at
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_article_mapping.update_at
     *
     * @param updateAt the value for tag_article_mapping.update_at
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}