package com.lee.mapper;

import com.lee.pojo.ArticleType;
import com.lee.pojo.ArticleTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    int countByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    int deleteByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    int insert(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    int insertSelective(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    List<ArticleType> selectByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    ArticleType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") ArticleType record, @Param("example") ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    int updateByExample(@Param("record") ArticleType record, @Param("example") ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    int updateByPrimaryKeySelective(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Sat Nov 19 16:53:30 CST 2022
     */
    int updateByPrimaryKey(ArticleType record);
}