package com.lee.mapper;

import com.lee.pojo.HasApproval;
import com.lee.pojo.HasApprovalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HasApprovalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table has_approval
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    int countByExample(HasApprovalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table has_approval
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    int deleteByExample(HasApprovalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table has_approval
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table has_approval
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    int insert(HasApproval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table has_approval
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    int insertSelective(HasApproval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table has_approval
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    List<HasApproval> selectByExample(HasApprovalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table has_approval
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    HasApproval selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table has_approval
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    int updateByExampleSelective(@Param("record") HasApproval record, @Param("example") HasApprovalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table has_approval
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    int updateByExample(@Param("record") HasApproval record, @Param("example") HasApprovalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table has_approval
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    int updateByPrimaryKeySelective(HasApproval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table has_approval
     *
     * @mbggenerated Wed Nov 23 14:21:42 CST 2022
     */
    int updateByPrimaryKey(HasApproval record);
}