package com.lee.mapper;

import com.lee.pojo.TagArticleMapping;
import com.lee.pojo.TagArticleMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagArticleMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article_mapping
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    int countByExample(TagArticleMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article_mapping
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    int deleteByExample(TagArticleMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article_mapping
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article_mapping
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    int insert(TagArticleMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article_mapping
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    int insertSelective(TagArticleMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article_mapping
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    List<TagArticleMapping> selectByExample(TagArticleMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article_mapping
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    TagArticleMapping selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article_mapping
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    int updateByExampleSelective(@Param("record") TagArticleMapping record, @Param("example") TagArticleMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article_mapping
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    int updateByExample(@Param("record") TagArticleMapping record, @Param("example") TagArticleMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article_mapping
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    int updateByPrimaryKeySelective(TagArticleMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article_mapping
     *
     * @mbggenerated Sat Nov 19 20:01:29 CST 2022
     */
    int updateByPrimaryKey(TagArticleMapping record);
}