package com.lee.mapper;

import com.lee.pojo.UserFollow;
import com.lee.pojo.UserFollowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Wed Nov 23 20:51:10 CST 2022
     */
    int countByExample(UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Wed Nov 23 20:51:10 CST 2022
     */
    int deleteByExample(UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Wed Nov 23 20:51:10 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Wed Nov 23 20:51:10 CST 2022
     */
    int insert(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Wed Nov 23 20:51:10 CST 2022
     */
    int insertSelective(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Wed Nov 23 20:51:10 CST 2022
     */
    List<UserFollow> selectByExample(UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Wed Nov 23 20:51:10 CST 2022
     */
    UserFollow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Wed Nov 23 20:51:10 CST 2022
     */
    int updateByExampleSelective(@Param("record") UserFollow record, @Param("example") UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Wed Nov 23 20:51:10 CST 2022
     */
    int updateByExample(@Param("record") UserFollow record, @Param("example") UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Wed Nov 23 20:51:10 CST 2022
     */
    int updateByPrimaryKeySelective(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Wed Nov 23 20:51:10 CST 2022
     */
    int updateByPrimaryKey(UserFollow record);
}